version: '3.5'

services:
  tabby:
    restart: always
    image: tabbyml/tabby
    command: serve --model TabbyML/StarCoder-1B
    volumes:
      - "$HOME/.tabby:/data"
    ports:
      - 8080:8080